name: PlatformChat
version: 1.1.0
main: com.aspaulding.platformchat.PlatformChat
api-version: 1.19
author: YourName
description: A plugin that shows player platforms in chat

# Optional dependencies
softdepend:
  - PlaceholderAPI
  - floodgate
  - EaglerXBackendRPC
