name: PlatformChat
version: 1.1.0
main: com.aspaulding.platformchat.PlatformChat
api-version: 1.19
author: aspaulding
description: A plugin that shows player platforms (Java, Bedrock, Eaglercraft) in chat

depend:
  - floodgate

softdepend:
  - PlaceholderAPI
  - EaglerXBackendRPC
